### ISSUE TITLE
Error when try load template!!

### ISSUE THREAD

**Issue by joaovmeneses** [PavelS0/docx_template_dart#1]
[#]The code :

  DocxTemplate docx = DocxTemplate();
  File f = File("assets/template.docx");
  await docx.load(f);

[#] The error:
E/flutter (18457): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: FileSystemException: Creation failed, path = 'docx_cache' (OS Error: Read-only file system, errno = 30)
----------------------------------------------------------------------------------------
Anybody help please. Thanks

**Comment by PavelS0** [comment]
Hi. Library trying to create temporary folder for unpack/pack docx file.
Exception says file system is READ ONLY. At this moment,  no support for in
memory unpacking. Try add param in constructor DocxTemplate
<https://pub.dev/documentation/docx_template/latest/docx_template/DocxTemplate/DocxTemplate.html>
(Directory cacheDir), where chacheDir path to writeable memory (idk where
is it, I'm not work with flutter).

вс, 22 мар. 2020 г., 20:38 joaovmeneses <notifications@github.com>:

**Comment by joaovmeneses** [comment]
Was it something like that?

Directory appDocDirectory = await getApplicationDocumentsDirectory();
  Directory(appDocDirectory.path+'/'+'docx_cache/').create().then((Directory directory) async {
    DocxTemplate docx = DocxTemplate(directory);
    docx.load(File("${directory.path}template.docx"));
    //docx.load(File("template.docx"));
  });

**Comment by PavelS0** [comment]
Where the template.docx file is located?
if in application document dir, then try

Directory appDocDirectory = await getApplicationDocumentsDirectory();
DocxTemplate('${appDocDirectory.path}/docx_cache');
docx.load(File("${appDocDirectory.path}/template.docx"));



пн, 23 мар. 2020 г., 20:39 joaovmeneses <notifications@github.com>:

**Comment by joaovmeneses** [comment]
I was think the template.docx to come with plugs. So i settled the template in 'assets', can i use in assets folder? If yes, how can i run docx.load() to load file in assets? Thanks so much man, really!

**Comment by PavelS0** [comment]
Try this:

var bytes = await rootBundle.load('assets/template.docx') ;  //don't forget
add asset in pubspec.yaml
File file =
MemoryFileSystem().file('template.dart')..writeAsBytesSync(bytes); // or
maybe bytes.asInt32List();
docx.load(file);

вт, 24 мар. 2020 г., 14:19 joaovmeneses <notifications@github.com>:

**Comment by joaovmeneses** [comment]
i needed add line :

    List<int> bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);

and haven't erro at here, but when i put the rest of code, returns

[ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: Exception: Cannot generate docx, template not loaded

**Comment by joaovmeneses** [comment]
The code 

void toDocx(BuildContext context) async {

  Directory appDocDirectory = await getApplicationDocumentsDirectory();

  Directory(appDocDirectory.path+'/'+'docx_cache/').create().then((Directory directory) async {

    DocxTemplate docx = DocxTemplate(directory);
    var data = await rootBundle.load('assets/template.docx') ;  //don't forgetadd asset in pubspec.yaml
    List<int> bytes = data.buffer.asUint8List(data.offsetInBytes, data.lengthInBytes);
    File file = MemoryFileSystem().file('template.dart')..writeAsBytesSync(bytes); // or maybe bytes.asInt32List();
    docx.load(file);
    generateDocx(docx);
  });

}

void generateDocx(DocxTemplate docx) async
{
  Content c = Content();
  c..add(TextContent("docname", "Simple docname"))
    ..add(TextContent("passport", "passport 1234 432134")
    );

  await docx.generate(c);
  await docx.save("generated.docx");

}

**Comment by PavelS0** [comment]
In version 0.2.0, File is no longer used. The Docx file is passed as an array of bytes. Temporary files are also not created; all operations are performed in memory.
