### ISSUE TITLE
style of the text in a list

### ISSUE THREAD

**Issue by briceAlex** [PavelS0/docx_template_dart#10]
Hi, 
I have this list :
Task: 

- **task1**  : task
- **task1**  : task
- **task1**  : task

I don't know how to have the bold side and the normal side text .

If you can help me please.

Thank you for your work !

**Comment by PavelS0** [comment]
Hi, you can  pass PlainContent instead of TextContent. And in PlainContent pass two TextContent's with different styles.
Like this:
![image](https://user-images.githubusercontent.com/6624721/113222255-3d382380-928f-11eb-89f1-a7f42d02e0a5.png)

Example code:
```
ListContent("listnested", [
    PlainContent("value")
      ..add(TextContent("normal", "BMW MTech"))
      ..add(TextContent("bold", "S55")),
    PlainContent("value")
      ..add(TextContent("normal", "BMW"))
      ..add(TextContent("bold", "N55")),
  ]
```

Result:
![image](https://user-images.githubusercontent.com/6624721/113222736-4a094700-9290-11eb-9526-7357ace7470e.png)

**Comment by briceAlex** [comment]
Hi, 
Thank you for your answer,
I understand, but I have a list of content like this : 

`               var listTaches = <Content>[];
                var listTachesCom = <Content>[];
                
                listTaches = afficheTache(db);
                listTachesCom = afficheTacheCom(db);

                c
                  ..add(TextContent("docname", "Simple test"))
                  ..add(ListContent("Taches",[
                    TextContent("value", "Tâches :")
                    ..add(ListContent("listnested", [
                      PlainContent("plain")
                        listTaches,
                      PlainContent("plain")
                        listTachesCom
                      
                    ])`

**Comment by PavelS0** [comment]
if I understood the problem correctly, in your example, one PlainContent contains only an array of text with a nomal style, and the second PlainContent contains only an array of text with a bold style.

Should be in one PlainContent both bold and normal style. The PlainContent will be the representation of the row in the list.
Example:
```
final listNormal = ['Foo', 'Bar', 'Baz'];
final listBold = ['ooF', 'raB', 'zaB'];

final contentList = <Content>[];

final b = listBold.iterator;
for (var n in listNormal) {
  // iterate two arrays syncronously
  b.moveNext();
  // add both normal text and bold text to PlainContent
  final c = PlainContent("value")
    ..add(TextContent("normal", n))
    ..add(TextContent("bold", b.current));
  // add PlainContent to List
  contentList.add(c);
}
// pass list to ListContent
c..add(ListContent("listnested", contentList));
```

**Comment by briceAlex** [comment]
Yes, I have a database (Hive), and yes I would like to display a normal and bold text on the same line in a list.

I follow your idea, but I have an issue, nothing is displayed : 
![listTag](https://user-images.githubusercontent.com/58272107/113417918-72796a00-9392-11eb-8552-07b5d5c64656.jpeg)

the code : 
`

              var contentList = <Content>[];

              // db is the database, var db = tacheBox.values;

              for (Tache n in db){

                  print(n.type+" = taches");
                  if(n.type=="tâches"){
                    final c = PlainContent("Plain")
                    ..add(TextContent("titre",n.titre))
                    ..add(TextContent("com",n.commentaire));       
                    contentList.add(c); 
                  }
                }
                c
                  ..add(TextContent("docname", "Simple test"))
                  ..add(ListContent("Taches",[
                    TextContent("value", "tâche :")
                    ..add(ListContent("listnested", contentList)
                    )]));
`
display : 
![image](https://user-images.githubusercontent.com/58272107/113417987-92a92900-9392-11eb-9ef6-db3c969eb817.png)

Thank you for your help.

**Comment by PavelS0** [comment]
`final c = PlainContent("Plain")`
&
![image](https://user-images.githubusercontent.com/6624721/113595533-cbbaf500-9641-11eb-85af-2b2778967334.png)

Tag names is case sensitive, so:
`final c = PlainContent("plain")`

**Comment by briceAlex** [comment]
Ho, thank you !
