### ISSUE TITLE
non-filled tags get deleted when generating file

### ISSUE THREAD

**Issue by marawanmo** [PavelS0/docx_template_dart#12]
i have a few tags which i dont want to get deleted when i dont fill them, enabling the option "never delete this tag" in word doesnt work, how can i do this?

**Comment by PavelS0** [comment]
at the moment, all tags are deleted during generation, I will try to add a flag for saving tags in the next update.

**Comment by marawanmo** [comment]
@PavelS0 thanks :)

**Comment by marawanmo** [comment]
@PavelS0 would you have a time estimate on the updata? id love to use this in my project

**Comment by PavelS0** [comment]
content inside tags now saved if it not filled

**Comment by marawanmo** [comment]
@PavelS0 thanks for working on this, but i wanted the tags to be saved, not the content inside them

**Comment by marawanmo** [comment]
@PavelS0 will this be fixed?

**Comment by PavelS0** [comment]
added in 5b786b9
added new enum:
```
/// [removeAll] - remove all sdt tags from document
///
/// [saveNullified] - save ONLY tags where [Content] is null
///
/// [saveText] - save ALL TextContent field (include nullifed [Content])
///
enum TagPolicy { removeAll, saveNullified, saveText }
```
it must be passed as argument
`docx.generate(c, tagPolicy: TagPolicy.saveNullified);`

**Comment by marawanmo** [comment]
works, thanks!
