### ISSUE TITLE
Null Safety support

### ISSUE THREAD

**Issue by wer-mathurin** [PavelS0/docx_template_dart#13]

**Comment by wer-mathurin** [comment]
I did a pull request #14 for at least make this libraries using the null safety version of it.

I did a little try upgrading this library to dart 2.12 to understand the effort.  It will not be a big deal...but I just need to understand a little more the logic in certain places.  As an example, some of your factories return null, and this is not allowed with null safety, here one example of factory that return null. 

`factory SdtView.parse(XmlElement e)`

 If you absolutely need to return null, you may need to convert this factory to an utility method.
`static SdtView? parse(XmlElement e)`

**Comment by PavelS0** [comment]
hi, I published the nullsafity alpha version

**Comment by wer-mathurin** [comment]
@PavelS0 What is the version number we can use from the pub.dev ?
