### ISSUE TITLE
FormatException: Could not find End of Central Directory Record

### ISSUE THREAD

**Issue by Arban960** [PavelS0/docx_template_dart#17]
When trying to run the example on [](https://pub.dev/packages/docx_template/example), I get FormatException: Could not find End of Central Directory Record. This is the code that I specifically used:
```
final data = await rootBundle.load('lib\\assets\\template.docx');
        final bytes = data.buffer.asUint8List();

        final docx = await DocxTemplate.fromBytes(bytes);
```

**Comment by PavelS0** [comment]
most likely, the path is not set correctly. Try using unix delimiters instead of windows i.e. 'assets/template.docx'
