### ISSUE TITLE
DOCX Template example is not working

### ISSUE THREAD

**Issue by burakcbdn** [PavelS0/docx_template_dart#18]
I am trying to create word document in my app, but when I use this package first I got error that says
=> ConcurrentModificationError (Concurrent modification during iteration: Instance(length:0) of '_GrowableList'.)

Then I think that I might wrote something wrong, then I copied example code and tried to run it but there is another error now.

=> _TypeError (type 'TextContent' is not a subtype of type 'PlainContent?' of 'c')

I did not change anything at all on the example code (just file paths)

I am using null safety pre-release because latest stable version gives  version solving errors.

Error:
<img width="1109" alt="Screen Shot 2021-05-21 at 00 16 25" src="https://user-images.githubusercontent.com/55558309/119050061-039bb300-b9ca-11eb-9c79-f1c3ac2eb6a5.png">

**Comment by marawanmo** [comment]
im also getting that error ^

**Comment by PavelS0** [comment]
fixed in 8db94ad9998060f1a7793c44b39392c44c6a2c30
