### ISSUE TITLE
Flutter Web support is missing.

### ISSUE THREAD

**Issue by mayurkothawade** [PavelS0/docx_template_dart#2]
Can we avoid using File or have alternate logic of using File using https://pub.dev/packages/file_access instead of dart:io's File .

**Comment by PavelS0** [comment]
In version 0.2.0, File is no longer used. The Docx file is passed as an array of bytes. Temporary files are also not created; all operations are performed in memory.

**Comment by mayurkothawade** [comment]
When is 0.2.0 getting released ?

**Comment by PavelS0** [comment]
> When is 0.2.0 getting released

Released a few hours ago in pub. 
https://pub.dev/packages/docx_template

**Comment by mayurkothawade** [comment]
Saw the code changes, Could you update your sample project as well?
