### ISSUE TITLE
Word file gets corrupted

### ISSUE THREAD

**Issue by AbdullahNaveed** [PavelS0/docx_template_dart#37]
I am trying to edit a very simple word file with 1 control tag.
Word file is fetched correctly and displayed, but when I use docGenerated = await docx.generate(c); 

The file gets corrupted. I am using Office 2016 to create word files.

<img width="366" alt="Screen Shot 2022-11-28 at 3 20 49 PM" src="https://user-images.githubusercontent.com/45510165/204265648-b89e49b7-89b0-4d0c-9ad4-4b8f8cef5f0f.png">

Code:
<img width="658" alt="Screen Shot 2022-11-28 at 3 21 16 PM" src="https://user-images.githubusercontent.com/45510165/204265718-780f5c50-5985-4de9-8755-7c6b938b5357.png">

**Comment by ShineYang** [comment]
Same problem, it's strange that I've already successfully generated target document fews days before, with the same code.
I tried to downgrade flutter sdk to earlier version (3.5 ~ 3.8) but it doesn't work.

**Comment by kungege** [comment]
@PavelS0 Could you take a look at this, please?

**Comment by ShineYang** [comment]
@AbdullahNaveed Found a temporary solution here, just override this dependency in `pubspec.yaml`
```
dependency_overrides:
  archive: 3.3.0
```

**Comment by AbdullahNaveed** [comment]
> @AbdullahNaveed Found a temporary solution here, just override this dependency in `pubspec.yaml`
> 
> ```
> dependency_overrides:
>   archive: 3.3.0
> ```

Works like a charm!!! Thanks so much brother <3

**Comment by weimuhua** [comment]
> @AbdullahNaveed Found a temporary solution here, just override this dependency in `pubspec.yaml`
> 
> ```
> dependency_overrides:
>   archive: 3.3.0
> ```

you save my life bro!

**Comment by marcov-dart** [comment]
As a hint to the maintainers:
I just came across this same problem in a bit of my own code. It worked for archive 3.3.0 but with archive 3.3.5 the resulting zip file is truncated.
I am reading a zip file into Archive and then making a new Archive copying adding of the original ArchiveFile objects but replacing some. Probably very similar to what is being done here. 
I had to make new ArchiveFile objects with the name, size and contents of the original (make a copy) and add that copy to the new archive instead of the ArchiveFile objects from the original.

**Comment by Terranic** [comment]
Great, thanks! 

this one seems to work as well, but with 3.3.3 the docx is becoming corrupted
`dependency_overrides:
  archive: 3.3.2`

**Comment by WilliansDutra** [comment]
I have the same problem.

I have tried with and without the dependency overrides, tried the code from sample, tried my own template file and template file from docs. 

I'm starting to get bald with this lol

![image](https://user-images.githubusercontent.com/30528586/220459118-e54ea7cf-2cf9-4f94-af00-efad4e68b341.png)
![image](https://user-images.githubusercontent.com/30528586/220459207-d3ac8369-4f2d-4c4a-bd31-7688f3dddda8.png)
![image](https://user-images.githubusercontent.com/30528586/220459313-0e408478-3f4f-4299-a578-ac9260bcda58.png)

**Comment by Fiat2U** [comment]
> Great, thanks!
> 
> this one seems to work as well, but with 3.3.3 the docx is becoming corrupted `dependency_overrides: archive: 3.3.2`

I used your code in https://github.com/Fiat2U/docx_template_flutter_sample.

**Comment by Fiat2U** [comment]
@WilliansDutra You may want to try https://github.com/Fiat2U/docx_template_flutter_sample.

**Comment by WilliansDutra** [comment]
@Fiat2U made a test using the link and it worked! Now I'll try within my project. I'll post here the update.

**Comment by PavelS0** [comment]
Probably fixed in de19046
