### ISSUE TITLE
word file can't opening

### ISSUE THREAD

**Issue by ahmetbalaman** [PavelS0/docx_template_dart#41]
Hello, I am trying to open generated.docx but I am seeing corrupted word file. and I can't opening.
can you help me?

**Comment by Fiat2U** [comment]
Please refer to https://github.com/PavelS0/docx_template_dart/issues/37 or my repository at https://github.com/Fiat2U/docx_template_flutter_sample.

**Comment by TriAriSetiawan** [comment]
same with me, when call function generate then file cant open because corrupted

**Comment by Fiat2U** [comment]
@ahmetbalaman @TriAriSetiawan For workarounds, please refer to my repository at https://github.com/Fiat2U/docx_template_flutter_sample or the related issue at https://github.com/PavelS0/docx_template_dart/issues/37.
