### ISSUE TITLE
How to add TextContent dynamically

### ISSUE THREAD

**Issue by briceAlex** [PavelS0/docx_template_dart#7]
Hi, 

I try to create a document like this dynamically : 

Title : 
// dynamically
- TextContent() 
- TextContent()
- TextContent()
-// end

Thank you for you work on this package !

**Comment by briceAlex** [comment]
I started with that : 
`Content c = Content();
               
                c
                  ..add(TextContent("docname", "Simple test"))
                  ..add(ListContent("Taches", [
                    TextContent("value", "Taches").add(ListContent(
                        "listnested", [
                      for (var i = 0; i < 10; i++)
                        TextContent("value", " i : ${i}")
                    ]))
                  ]));
`

**Comment by PavelS0** [comment]
hi,
like this:

`  Content c = Content();

  final list = <Content>[];
  for (var i = 0; i < 10; i++) list.add(TextContent("value", " i : ${i}"));

  c
    ..add(TextContent("docname", "Simple test"))
    ..add(ListContent("Taches", list));`

**Comment by briceAlex** [comment]
Hi, 
all works well thanks to you !
