### ISSUE TITLE
Generated file becomes corrupted with multiple images (question?)

### ISSUE THREAD

**Issue by marawanmo** [PavelS0/docx_template_dart#9]
https://stackoverflow.com/questions/66770150/dart-generated-docx-file-gets-corrupted

I have left this question, i dont know if it is an issue with my code or with the package and i would appriciate it if someone could take a look at it.

**Comment by marawanmo** [comment]
after trying some things i noticed that when i set more then one label to img the file corrupted, what am i supossed to do if i want more than 1 image?

**Comment by marawanmo** [comment]
@shalika-97 sadly i havent ;/ ive also noticed that the tags which dont get filled get deleted on generation. please do let me know if you found a solution

**Comment by PavelS0** [comment]
Fixed in a864546

**Comment by marawanmo** [comment]
@PavelS0 ok thanks that works now, but the tags which dont get filled get deleted, what is the fix for this?
